'''Creates unpaired MSAs in af3 format to use as AlphaFold input.'''
import sys 
sys.path.append('/home/prichter/Documents/banfield/betazoid/src/')
sys.path.append('/home/prichter/Documents/banfield/betazoid/src/files/')

import numpy as np
import pandas as pd 
from dataclasses import dataclass
import shutil 
import os
import re
import argparse
import glob 
import subprocess

from fasta import FASTAFile 


ROOT_DIR = '/home/prichter/Documents/banfield/betazoid'

OUTPUT_DIRS = dict()
OUTPUT_DIRS['a3m'] = os.path.join(ROOT_DIR, 'data/genes/mmseqs')
OUTPUT_DIRS['afa'] = os.path.join(ROOT_DIR, 'data/genes/muscle')


DATABASE_DIR = os.path.join(OUTPUT_DIRS['a3m'], 'db')
DATABASE_NAME = 'database'
TMP_DIR = os.path.join(OUTPUT_DIRS['a3m'], 'tmp')

MIN_SEQ_IDENTITY = 0.95
MIN_COVERAGE = 0.95 
COVERAGE_MODE = 5
SENSITIVITY = 9.5

@dataclass
class Databases:
    input: str
    output_search: str
    output_align: str
    output_msa: str


def msa_build_a3m_cleanup(msa_paths:list, database_dir:str=DATABASE_DIR):
    '''Clean up the databases and directories created for MSA generation.
    
    :param msa_paths: A list of output MSAs to remove from the output directory. These are the MSAs failing the keep_msa condition
        defined in the msa_build_a3m function. 
    :returns: None
    '''
    for path in glob.glob(os.path.join(database_dir, f'{DATABASE_NAME}*')): 
        os.remove(path)
    shutil.rmtree(TMP_DIR, ignore_errors=True)

    print(f'msa_build_a3m_cleanup: Removing {len(msa_paths)} output MSAs which do not match a specified query ID.')
    for msa_path in msa_paths:
        os.remove(msa_path)


def msa_dereplicate_cleanup(output_path:str):
    '''Clean up the files created for sequence dereplication.
    
    :param output_path: The prefix for the output files generated by MMseqs easy-cluster. 
    :returns: None
    '''
    # Clean up the output files. 
    for extension in ['_cluster.tsv', '_rep_seq.fasta', '_all_seqs.fasta']:
        os.remove(output_path + extension)


def msa_dereplicate(path, output_dir=None, query_gene_ids:list=None, min_seq_identity:float=MIN_SEQ_IDENTITY, min_coverage=MIN_COVERAGE, coverage_mode:int=COVERAGE_MODE, **kwargs):
    '''

    :param output_dir: 
    :param query_gene_ids: The IDs of sequences which will be input to AlphaFold, and therefore require an af3 MSA where they are the 
        reference sequence (i.e. in the first line of the file). If this argument is specified, all MSAs which do not use one of these 
        sequences as the reference sequence are removed from output_dir. 
    :param min_seq_identity:
    :param min_coverage:
    :param coverage_mode

    '''
    name = os.path.basename(path).split('.')[0]
    output_path = os.path.join(output_dir, name)
    cmd = f'mmseqs easy-cluster {path} {output_path} {TMP_DIR} --cov-mode {coverage_mode} -c {min_coverage} --min-seq-id {min_seq_identity}'
    # print(cmd)
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.DEVNULL)

    # Load the mmseqs clusters and select representatives, ensuring the MSA queries are included in the final set. 
    cluster_df = pd.read_csv(output_path + '_cluster.tsv', names=['rep_gene_id', 'gene_id'], sep='\t')

    if query_gene_ids is not None:
        cluster_df['is_query'] = cluster_df.gene_id.isin(query_gene_ids)
        cluster_df = cluster_df.sort_values('is_query', ascending=False)

    cluster_df = cluster_df.drop_duplicates('rep_gene_id')
    assert np.all(np.isin(query_gene_ids, cluster_df.gene_id.unique())), f'msa_dereplicate: Some query IDs are missing from the set of dereplicated sequences.'

    reps_df = FASTAFile.from_file(path).to_df()
    reps_df = reps_df.loc[cluster_df.gene_id.values].copy()
    FASTAFile.from_df(reps_df).write(os.path.join(output_dir, f'{name}_reps.faa'))

    msa_dereplicate_cleanup(output_path)

    print(f'msa_dereplicate: {len(reps_df)} representative sequences when clustered at {min_seq_identity} minimum identity.')
    return reps_df, os.path.join(output_dir, f'{name}_reps.faa')




def msa_build_a3m(path:str, output_dir:str=None, query_gene_ids:list=None, database_dir:str=DATABASE_DIR, sensitivity=SENSITIVITY, **kwargs):
    '''Use MMseqs align utilities to construct a3m-format alignment files for each sequence in the input FASTA file. The pipeline
    is as follows:
        (1) Use the input FASTA file to construct an MMseqs database. 
        (2) Generate a search result database by querying the input database against itself. 
        (3) Construct full alignments using the results of the search. 
        (4) Convert the alignments to MSAs. 
        (5) Unpack the alignment output info a3m files compatible with AlphaFold; there will be one file per query.
        
    :param path: The path to the FASTA file containing all sequences to use in MSA construction.
    :param output_dir: The directory where all output files will be deposited. 
    :param query_gene_ids: The IDs of sequences which will be input to AlphaFold, and therefore require an af3 MSA where they are the 
        reference sequence (i.e. in the first line of the file). If this argument is specified, all MSAs which do not use one of these 
        sequences as the reference sequence are removed from output_dir. 
    :param sensitivity: The search sensitivity for the initial MMseqs search step. 
    '''

    database_path = os.path.join(database_dir, DATABASE_NAME)
    databases = Databases(database_path, f'{database_path}.out', f'{database_path}.aln', f'{database_path}.msa')

    kwargs = {'shell':True, 'check':True, 'stdout':subprocess.DEVNULL}
    cmds = [f'mmseqs createdb {path} {databases.input}']
    cmds += [f'mmseqs search {databases.input} {databases.input} {databases.output_search} {TMP_DIR} -s {sensitivity}']
    cmds += [f'mmseqs align {databases.input} {databases.input} {databases.output_search} {databases.output_align}']
    cmds += [f'mmseqs result2msa {databases.input} {databases.input} {databases.output_align} {databases.output_msa}']
    cmds += [f'mmseqs unpackdb {databases.output_msa} {output_dir} --unpack-suffix .a3m']

    for cmd in cmds:
        print('msa_build_a3m:', cmd)
        subprocess.run(cmd, **kwargs)

    msa_paths = list()

    # The unpacked database files just have numerical IDs, so want to rename according to their actual gene IDs. 
    # This is done by mapping the numerical ID to the original gene ID using the lookup table associated with the input database. 
    num_to_gene_id_map = pd.read_csv(databases.input + '.lookup', sep=r'\s+', names=['num', 'gene_id'], index_col=0, usecols=[0, 1]).gene_id.to_dict()

    for file_name in os.listdir(output_dir):
        if not re.match(r'\d+\.a3m', file_name):
            continue 
        n = int(re.match(r'(\d+)\.a3m', file_name).group(1))
        old_path = os.path.join(output_dir, file_name)
        new_path = os.path.join(output_dir, f'{num_to_gene_id_map[n]}.a3m')
        subprocess.run(f'mv {old_path} {new_path}', shell=True, check=True)

        msa_paths.append(new_path)

    print(f'msa_build_a3m: Generated {len(msa_paths)} total MSAs.')
    pattern = '|'.join([gene_id.replace('.', r'\.') for gene_id in query_gene_ids]) if (query_gene_ids is not None) else r'.*'
    keep_msa = lambda msa_path : re.search(pattern, msa_path) is not None 

    msa_build_a3m_cleanup([msa_path for msa_path in msa_paths if (not keep_msa(msa_path))], database_dir=database_dir)

    return [msa_path for msa_path in msa_paths if keep_msa(msa_path)]


# def msa_print_stats(msa_paths):

#     get_num_insertions = lambda seq : sum(char.islower() for char in seq)
#     get_num_deletions = lambda seq : seq.count('-')


#     for path in msa_paths:
#         print(f'\n{os.path.basename(path)}')
#         fasta_file = FASTAFile.from_file(path)
#         print('Query length:', len(fasta_file.seqs[0]))
#         print('Number of sequences:',len(fasta_file) - 1)
#         print('Average number of insertions:', f'{np.mean([get_num_insertions(seq) for seq in fasta_file.seqs[1:]]):.2f}')
#         print('Average number of deletions:',  f'{np.mean([get_num_deletions(seq) for seq in fasta_file.seqs[1:]]):.2f}')


def msa_build_afa(path:str, name:str=None, output_dir:str=None, max_gap_fraction:float=0.8, **kwargs):
    '''

    :param max_gap_fraction: If more than this fraction of the sequences have a gap at any position, then trim the column. 
    
    '''

    # msa_file_name, _ = os.path.splitext(os.path.basename(path))
    msa_path = os.path.join(output_dir, f'{name}.afa')
    trimmed_msa_path = os.path.join(output_dir, f'{name}.trimmed.afa')
    path, msa_path = os.path.abspath(path), os.path.abspath(msa_path)
    trimmed_msa_path = os.path.abspath(trimmed_msa_path)

    cmds = [f'muscle -align {path} -output {msa_path}']
    cmds += [f'clipkit {msa_path} -o {trimmed_msa_path} -g {max_gap_fraction} --log']
    # cmds += [f'clipkit {msa_path} -o {trimmed_msa_path} -g {max_gap_fraction} --log {trimmed_msa_log_path}']
    for cmd in cmds:
        print('msa_build_afa:', cmd)
        subprocess.run(cmd, shell=True, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return [trimmed_msa_path]
    


def msa_main(path:str, fmt:str='afa', name:str=None, output_dir:str=None, database_dir:str=None, query_gene_ids:list=None, **kwargs):
    '''Run the msa_dereplicate and msa_build_a3m functions in succession. 

    :param path: The path to the FASTA file containing all sequences to use in MSA construction.
    :param fmt: The type of MSA to generate. 
    :param output_dir: The directory where all final a3m files will be deposited. 
    :param database_dir: The directory for the intermediate MMseqs databases..    
    :param query_gene_ids: The IDs of sequences which will be input to AlphaFold, and therefore require an af3 MSA where they are the 
        reference sequence (i.e. in the first line of the file). If this argument is specified, all MSAs which do not use one of these 
        sequences as the reference sequence are removed from output_dir. 
    :returns: A list of the final paths to the MSAs in a3m format.
    '''
    # print(f'msa_main: Output directory is {output_dir}')
    # print(f'msa_main: Database directory is {database_dir}')


    name = os.path.splitext(os.path.basename(path))[0] if (name is None) else name

    _, path = msa_dereplicate(path, query_gene_ids=query_gene_ids, output_dir=output_dir, **kwargs)

    if fmt == 'a3m':
        msa_paths = msa_build_a3m(path, database_dir=database_dir, query_gene_ids=query_gene_ids, output_dir=output_dir, **kwargs)
    elif fmt == 'afa':
        msa_paths = msa_build_afa(path, name=name, output_dir=output_dir, **kwargs)
    else:
        raise Exception(f'msa_main: Format {fmt} is invalid.')

    # msa_print_stats(msa_paths)
    return msa_paths



if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('path', type=str)
    parser.add_argument('--fmt', required=True, type=str, default='afa')
    parser.add_argument('--name', required=False, type=str, default=None)
    parser.add_argument('--query-gene-ids', default=None, nargs='+')    
    parser.add_argument('--output-dir', type=str, default=None)
    parser.add_argument('--database-dir', type=str, default=DATABASE_DIR)
    # Arguments for msa_build_a3m.
    parser.add_argument('--sensitivity', type=float, default=SENSITIVITY)
    # Arguments for msa_dereplicate.
    parser.add_argument('--min-seq-identity', type=float, default=MIN_SEQ_IDENTITY)
    parser.add_argument('--coverage-mode', type=int, default=COVERAGE_MODE)
    parser.add_argument('--min-coverage', type=float, default=MIN_COVERAGE)

    args = parser.parse_args()

    if args.output_dir is None:
        args.output_dir = OUTPUT_DIRS[args.fmt]

    msa_main(args.path, **vars(args))