'''Creates unpaired MSAs in af3 format to use as AlphaFold input.'''
import sys 
sys.path.append('/home/prichter/Documents/banfield/betazoid/src/')

import numpy as np
import pandas as pd 
from dataclasses import dataclass
import shutil 
import os
import re
import glob 
import subprocess

from files.fasta import FASTAFile 

DATABASE_NAME = 'database'

ROOT_DIR = '/home/prichter/Documents/banfield/betazoid'
TMP_DIR = os.path.join(ROOT_DIR, 'data', 'genes', 'mmseqs', 'tmp')


MIN_SEQ_IDENTITY = 0.95
MIN_COVERAGE = 0.95 
COVERAGE_MODE = 5
SENSITIVITY = 9.5
NUM_ITERATIONS = 5 

@dataclass
class Databases:
    input: str
    output_search: str
    output_align: str
    output_msa: str


def msa_get_a3m_cleanup(msa_paths:list, database_dir:str=None, database_name:str=None):
    '''Clean up the databases and directories created for MSA generation.
    
    :param msa_paths: A list of output MSAs to remove from the output directory. These are the MSAs failing the keep_msa condition
        defined in the msa_get_a3m function. 
    :returns: None
    '''
    for path in glob.glob(os.path.join(database_dir, f'{database_name}*')): 
        os.remove(path)
    shutil.rmtree(TMP_DIR, ignore_errors=True)

    print(f'msa_get_a3m_cleanup: Removing {len(msa_paths)} output MSAs which do not match a specified query ID.')
    for msa_path in msa_paths:
        os.remove(msa_path)


def msa_dereplicate_cleanup(output_path:str):
    '''Clean up the files created for sequence dereplication.
    
    :param output_path: The prefix for the output files generated by MMseqs easy-cluster. 
    :returns: None
    '''
    # Clean up the output files. 
    for extension in ['_cluster.tsv', '_rep_seq.fasta', '_all_seqs.fasta']:
        os.remove(output_path + extension)


def msa_dereplicate(path, output_dir=None, query_gene_ids:list=None, min_seq_identity:float=MIN_SEQ_IDENTITY, min_coverage=MIN_COVERAGE, coverage_mode:int=COVERAGE_MODE, **kwargs):
    '''

    :param output_dir: 
    :param query_gene_ids: The IDs of sequences which will be input to AlphaFold, and therefore require an af3 MSA where they are the 
        reference sequence (i.e. in the first line of the file). If this argument is specified, all MSAs which do not use one of these 
        sequences as the reference sequence are removed from output_dir. 
    :param min_seq_identity:
    :param min_coverage:
    :param coverage_mode

    '''

    print(f'msa_dereplicate: min_coverage = {min_coverage}')
    print(f'msa_dereplicate: min_seq_identity = {min_seq_identity}')
    print(f'msa_dereplicate: coverage_mode = {coverage_mode}')

    name = os.path.basename(path).split('.')[0]
    output_path = os.path.join(output_dir, name)
    cmd = f'mmseqs easy-cluster {path} {output_path} {TMP_DIR} --cov-mode {coverage_mode} -c {min_coverage} --min-seq-id {min_seq_identity}'
    # print(cmd)
    subprocess.run(cmd, shell=True, check=True, stdout=subprocess.DEVNULL)

    # Load the mmseqs clusters and select representatives, ensuring the MSA queries are included in the final set. 
    cluster_df = pd.read_csv(output_path + '_cluster.tsv', names=['rep_gene_id', 'gene_id'], sep='\t')

    if query_gene_ids is not None:
        cluster_df['is_query'] = cluster_df.gene_id.isin(query_gene_ids)
        cluster_df = cluster_df.sort_values('is_query', ascending=False)

    # If two queries end up in the same cluster, this can cause problems, because one will be dropped either way, causing this to throw an error.
    # Therefore, we take the union of the query IDs and de-replicated sequences. 
    filter_ = ~cluster_df.duplicated('rep_gene_id', keep='first')
    gene_ids = cluster_df[filter_].gene_id.unique() # First pass of dereplicated gene IDs. 
    # assert np.all(np.isin(query_gene_ids, gene_ids)), f'msa_dereplicate: Some query IDs are missing from the set of dereplicated sequences.'
    if not np.all(np.isin(query_gene_ids, gene_ids)):
        print(f'msa_dereplicate: Some of the query IDs were dropped by dereplication. Manually adding {(~np.isin(query_gene_ids, gene_ids)).sum()} IDs.')
        gene_ids = np.unique(gene_ids.tolist() + list(query_gene_ids))

    print(f'msa_dereplicate: {len(cluster_df)} sequences in the input file.')
    print(f'msa_dereplicate: {len(gene_ids)} sequences remaining after dereplication.')

    reps_df = FASTAFile.from_file(path).to_df()
    reps_df = reps_df.loc[gene_ids].copy()
    reps_df = reps_df[~reps_df.index.duplicated(keep='first')].copy()
    FASTAFile.from_df(reps_df).write(os.path.join(output_dir, f'{name}_reps.faa'))

    msa_dereplicate_cleanup(output_path)

    # print(f'msa_dereplicate: {len(reps_df)} representative sequences when clustered at {min_seq_identity} minimum identity.')
    return reps_df, os.path.join(output_dir, f'{name}_reps.faa')




def msa_get_a3m(path:str, output_dir:str=None, query_gene_ids:list=None, database_dir:str=None, sensitivity=SENSITIVITY, num_iterations:int=NUM_ITERATIONS, database_name:str='tmp', **kwargs):
    '''Use MMseqs align utilities to construct a3m-format alignment files for each sequence in the input FASTA file. The pipeline
    is as follows:
        (1) Use the input FASTA file to construct an MMseqs database. 
        (2) Generate a search result database by querying the input database against itself. 
        (3) Construct full alignments using the results of the search. 
        (4) Convert the alignments to MSAs. 
        (5) Unpack the alignment output info a3m files compatible with AlphaFold; there will be one file per query.
        
    :param path: The path to the FASTA file containing all sequences to use in MSA construction.
    :param output_dir: The directory where all output files will be deposited. 
    :param query_gene_ids: The IDs of sequences which will be input to AlphaFold, and therefore require an af3 MSA where they are the 
        reference sequence (i.e. in the first line of the file). If this argument is specified, all MSAs which do not use one of these 
        sequences as the reference sequence are removed from output_dir. 
    :param sensitivity: The search sensitivity for the initial MMseqs search step. 
    '''
    database_path = os.path.join(database_dir, database_name)
    databases = Databases(database_path, f'{database_path}.out', f'{database_path}.aln', f'{database_path}.msa')

    print(f'msa_get_a3m: num_iterations = {num_iterations}')
    print(f'msa_get_a3m: sensitivity = {sensitivity}')

    kwargs = {'shell':True, 'check':True, 'stdout':subprocess.DEVNULL}
    cmds = [f'mmseqs createdb {path} {databases.input}']
    cmds += [f'mmseqs search {databases.input} {databases.input} {databases.output_search} {TMP_DIR} -s {sensitivity} --num-iterations {num_iterations}']
    cmds += [f'mmseqs align {databases.input} {databases.input} {databases.output_search} {databases.output_align}']
    cmds += [f'mmseqs result2msa {databases.input} {databases.input} {databases.output_align} {databases.output_msa}']
    cmds += [f'mmseqs unpackdb {databases.output_msa} {output_dir} --unpack-suffix .a3m']

    for cmd in cmds:
        print('msa_get_a3m:', cmd)
        subprocess.run(cmd, **kwargs)

    msa_paths = list()

    # The unpacked database files just have numerical IDs, so want to rename according to their actual gene IDs. 
    # This is done by mapping the numerical ID to the original gene ID using the lookup table associated with the input database. 
    num_to_gene_id_map = pd.read_csv(databases.input + '.lookup', sep=r'\s+', names=['num', 'gene_id'], index_col=0, usecols=[0, 1]).gene_id.to_dict()

    for file_name in os.listdir(output_dir):
        if not re.match(r'\d+\.a3m', file_name):
            continue 
        n = int(re.match(r'(\d+)\.a3m', file_name).group(1))
        old_path = os.path.join(output_dir, file_name)
        new_path = os.path.join(output_dir, f'{num_to_gene_id_map[n]}.a3m')
        subprocess.run(f'mv {old_path} {new_path}', shell=True, check=True)

        msa_paths.append(new_path)

    print(f'msa_get_a3m: Generated {len(msa_paths)} total MSAs.')
    pattern = '|'.join([gene_id.replace('.', r'\.') for gene_id in query_gene_ids]) if (query_gene_ids is not None) else r'.*'
    keep_msa = lambda msa_path : re.search(pattern, msa_path) is not None 

    msa_get_a3m_cleanup([msa_path for msa_path in msa_paths if (not keep_msa(msa_path))], database_dir=database_dir, database_name=database_name)

    return [msa_path for msa_path in msa_paths if keep_msa(msa_path)]